/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * interfaz.java
 *
 * Created on 31-may-2012, 11:08:37
 */
package SE;

import java.awt.BorderLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;
import jess.ConsolePanel;

/**
 *
 * @author flavio
 */
public class interfaz extends javax.swing.JFrame {

    ConsolePanel c;
    public javax.swing.JLabel jLabel5 = new JLabel();

    /** Creates new form interfaz */
    public interfaz(ConsolePanel c) {
        initComponents();
        this.c = c;
        this.add(c, BorderLayout.CENTER);
        this.jPanel2.setLayout(new BorderLayout());
        this.jPanel2.add(jLabel3, BorderLayout.NORTH);
        this.jPanel2.add(jLabel5, BorderLayout.SOUTH);
//        JPanel j = new JPanel();
//        j.setLayout(new BorderLayout());
//        j.add(c, BorderLayout.CENTER);
//        jScrollPane1.getViewport().setView(j);
        this.setExtendedState(MAXIMIZED_BOTH);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SE");

        jLabel3.setText("Probabilidad: ");
        jPanel2.add(jLabel3);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
